apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  namespace: monitoring
  labels:
    release: prometheus  # ✅ Must match label on your Prometheus CR
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-postgres-exporter
      app.kubernetes.io/instance: postgres-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
      interval: 15s
