# hpa-backend.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: capsp-backend-hpa
  namespace: jakir007-capsp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: capsp-backend
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
